name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  rust:
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    defaults:
      run:
        working-directory: rust

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}-build-script-${{ hashFiles('build.rs') }}

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          profile: minimal

      - name: Run tests
        run: cargo test --release

      - name: Run tests with Arb
        run: cargo test --release --features "arb"

      - name: Clippy
        run: cargo clippy --all-targets -- -Dwarnings

      - name: Check format
        run: cargo fmt -- --check

  app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - run: npm ci

      - run: npm run build:app
        env:
          NODE_ENV: production

      #- run: npm test

      - run: npm run lint
