name: rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: rust

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          profile: minimal

      - name: Run tests
        run: cargo test --release

      - name: Clippy
        run: cargo clippy --all-targets -- -Dwarnings

      - name: Check format
        run: cargo fmt -- --check
